spring:
  application:
    name: library-manager

  datasource:
    url: jdbc:mysql://localhost:3306/personal_library
    username: root
    password: "detachment&2011"
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, beans

google:
  books:
    api:
      key: AIzaSyAXknYCjs5Yxk3Jy1SnvB85Mslqb998bHY